### ISSUE TITLE
Non-recoverable error when converting blueprint book to water placeable

### ISSUE THREAD

**Issue by Nebisan** [KeinNiemand/Factorio-GhostOnWater#26]
When I convert a blueprint book in my inventory to water placeable (using either the toolbar button or the keyboard shortcut, a non-recoverable error occurs with the following error message.

https://imgur.com/a/YU7t7nb

This doesn't seem to be the case for other blueprint books, just this one.

**Comment by KeinNiemand** [comment]
There's currently a bug that causes a crash when trying to convert a blueprint with no entities in it (blueprints which only have tiles like concrete or landfill or whatever in it) if that's the case for your blueprint book then this is a duplicate of #25
