### ISSUE TITLE
Rail/chain signals are not marking trees/rocks for deconstruction

### ISSUE THREAD

**Issue by ChaosSaber** [KeinNiemand/Factorio-GhostOnWater#30]
If you have a blueprint with rail and/or chain signals then the ghost on water version is not marking trees or rocks for deconstruction. They are just sitting there and waiting until the tree/rock is manually removed. Happens with vanilla and only ghost on water installed.
Maybe related to this issue: https://mods.factorio.com/mod/GhostOnWater/discussion/63598d137533c4faf851108c

**Comment by KeinNiemand** [comment]
Probably not related to the list, probably caused by the water ghosts not colliding with trees or rocks.

**Comment by ChaosSaber** [comment]
Seems like rail signals are not handled by the addAlternativeLayerForSpeicalRemovals funtion. Any idea why?
BTW, you can close this issue as duplicate in favor of #21 as they are both nearly the same issue, if you want to.
