### ISSUE TITLE
Blueprinted rail chain signal is not engaged to track correctly.

### ISSUE THREAD

**Issue by oEjk** [KeinNiemand/Factorio-GhostOnWater#31]
I am not sure if this is fixable, and there are workarounds.

But if GOW print of just chain signals is placed next to rails, they do not engage the rail properly.

A full blueprint works.

**Comment by KeinNiemand** [comment]
Probably related to water ghost beings different entities, I may look into it eventually but I don't know if there's anything I can do, might be unfixable
