### ISSUE TITLE
Nanobots won't build GhostOnWater-ified blueprints

### ISSUE THREAD

**Issue by espenhw** [KeinNiemand/Factorio-GhostOnWater#38]
I don't know if this is a bug with Nanobots or GhostOnWater.

In case it matters, I've tested as follows (using Factorio 1.1.78, Nanobots 3.2.19 and GhostOnWater 0.11.4):

- Create a new game
- Cheat in a nano emitter, some ammo, and some landfill
  ```
  /c game.player.insert{name="gun-nano-emitter", count=1}
  /c game.player.insert{name="ammo-nano-constructors", count=100}
  /c game.player.insert{name="landfill", count=100}
  ```
- Place a stone furnace and copy it
- Hit Ctrl+W to GhostOnWater-ify
- Paste on water
- TAB to activate the nano emitter

Shift-placing a stone furnace has nanobots build it, as well as shift-placing landfill on water.

If I cheat in the necessary bits to have vanilla construction bots, the GhostOnWater-ified blueprint gets built.

**Comment by KeinNiemand** [comment]
I know this issue tough I'm pretty sure this is a nanobots problem, it works with the regular bots so my guess is that nanobots does some kind of addional unnecessary check that vanilla bots don't that prevents them from building landfill if a ghost is on top. I don't think there's anything I can do to fix (other then reporting the bug to nanobots).
