### ISSUE TITLE
Train stop train limit not preserve when change blueprint into water placable.

### ISSUE THREAD

**Issue by AlpacaStorm** [KeinNiemand/Factorio-GhostOnWater#42]
As title

**Comment by KeinNiemand** [comment]
Weird, I'm pretty sure this used to work fine (or maybe I just never noticed), so maybe it's a vanilla bug. Also the train stop limit dosn't get lost when converting to water placeable (if you convert it back it's still there so it's preserved in the blueprint), it get's lost when the ghost get's upgraded back to the normal ghost. It get's lost when you upgrade train stops in general, which might be a bug in Factorio.

**Comment by KeinNiemand** [comment]
Yep it's confirmed to be a bug in Factorio and will be fixed in 1.1.93
https://forums.factorio.com/viewtopic.php?f=7&t=109034
